insert into donor (donor_name, donor_email, donor_pw, coin) values ('anonymous', 'anonymous', crypt('anonymous', gen_salt('bf')), 0);
insert into donor (donor_name, donor_email, donor_pw, coin) values ('John Smith', 'dyeomans0@telegraph.co.uk', crypt('V8lU6R3f', gen_salt('bf')), 5);
insert into donor (donor_name, donor_email, donor_pw, coin) values ('Lee Ziqi', 'akupker1@state.tx.us', crypt('M6tOaamSFND8', gen_salt('bf')), 87);
insert into donor (donor_name, donor_email, donor_pw, coin) values ('Jane Doe', 'jwelbeck2@umich.edu', crypt('8fMcK3mWEZ', gen_salt('bf')), 60);
insert into donor (donor_name, donor_email, donor_pw, coin) values ('Amirah Fatiqah', 'asimonnet3@liveinternet.ru', crypt('cMTDFyRJ', gen_salt('bf')), 98);
insert into donor (donor_name, donor_email, donor_pw, coin) values ('Billy Bob', 'rkayes4@shareasale.com', crypt('a0i6tF1z', gen_salt('bf')), 0);
insert into donor (donor_name, donor_email, donor_pw, coin) values ('Chris Chan', 'apetrelluzzi5@mac.com', crypt('SoJG76gJ4J', gen_salt('bf')), 48);
insert into donor (donor_name, donor_email, donor_pw, coin) values ('Jacques Lorenz', 'cyarnell6@technorati.com', crypt('MjMrTBlQp', gen_salt('bf')), 85);
insert into donor (donor_name, donor_email, donor_pw, coin) values ('Michael Jackson', 'gyarranton7@google.es', crypt('AdhUzRFvq', gen_salt('bf')), 39);
insert into donor (donor_name, donor_email, donor_pw, coin) values ('Jmmy Fallon', 'cburr8@nationalgeographic.com', crypt('5Dt8rVHc6bP', gen_salt('bf')), 60);
insert into donor (donor_name, donor_email, donor_pw, coin) values ('Remmy Zia', 'krowena9@de.vu', crypt('s9DLyQhGg', gen_salt('bf')), 84);
insert into donor (donor_name, donor_email, donor_pw, coin) values ('Shakira Isabel', 'bblawa@elpais.com', crypt('IPQWVLu5CGL', gen_salt('bf')), 25);
insert into donor (donor_name, donor_email, donor_pw, coin) values ('Kobe Bryant', 'eraynardb@shareasale.com', crypt('qYBzVErTi', gen_salt('bf')), 55);