insert into food (food_name, food_desc) values ('Spaghetti', 'vestibulum vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae nulla');
insert into food (food_name, food_desc) values ('Steak', 'ante nulla justo aliquam quis turpis eget elit sodales scelerisque mauris sit amet');
insert into food (food_name, food_desc) values ('Char Kway Tiao', 'tempus sit amet sem fusce consequat nulla nisl nunc nisl duis bibendum felis sed interdum venenatis turpis');
insert into food (food_name, food_desc) values ('Rojak', 'justo morbi ut odio cras mi pede malesuada in imperdiet');
insert into food (food_name, food_desc) values ('Ramen', 'nulla dapibus dolor vel est donec odio justo et eros ac est lacinia nisi venenatis tristique fusce congue diam');
insert into food (food_name, food_desc) values ('Sushi', 'luctus nec molestie sed justo pellentesque viverra pede ac diam cras volutpat dui maecenas tristique est');
insert into food (food_name, food_desc) values ('Dim Sum', 'ac enim in tempor turpis nec euismod scelerisque quam turpis adipiscing lorem vitae mattis nibh ligula nec sem duis');
insert into food (food_name, food_desc) values ('Peking Duck', 'sit amet nunc viverra dapibus nulla suscipit ligula in lacus curabitur sit amet nulla quisque arcu libero rutrum ac lobortis');
insert into food (food_name, food_desc) values ('Hamburger', 'mattis egestas metus aenean fermentum donec ut mauris eget massa eget eleifend luctus usto sit amet sapien dignissim');
insert into food (food_name, food_desc) values ('Fried Chicken', 'eu nibh quisque id justo sit amet sapien dignissim vestibulum vestibulum ante ipsum primis in faucibus');
insert into food (food_name, food_desc) values ('Coffee', 'maecenas tincidunt lacus at velit vivamus vel nulla eget erat quisque erat eros viverra eget congue eget semper');
insert into food (food_name, food_desc) values ('Milk Tea', 'ullamcorper augue a suscipit nulla elit ac amet nunc viverra dapibus nulla suscipit ligula in lacus curabitur at ipsum ac');
insert into food (food_name, food_desc) values ('Prata', 'vestibulum proin eu mi nulla ac enim in quam turpis adipiscing lorem vitae mattis nibh ligula nec sem duis aliquam');
insert into food (food_name, food_desc) values ('Butter Chicken', 'integer non velit donec diam neque vestibulum eget vulputate ut ultrices vel ante ipsum primis in faucibus orci luctus');
insert into food (food_name, food_desc) values ('Cake', 'vel nisl duis ac nibh fusce lacus purus aliquet at feugiat non pretium quis lectus suspendisse potenti');
insert into food (food_name, food_desc) values ('Ice-Cream', 'viverra diam vitae quam suspendisse potenti nullam donec posuere metus vitae mauris morbi non lectus aliquam sit amet diam');

insert into produced_by (merchant_email, food_sn) values ('western0@odnoklassniki.ru', '4d8b8191-ad57-4ccc-9b31-72574ac68953');
insert into produced_by (merchant_email, food_sn) values ('western0@odnoklassniki.ru', 'f2ca487b-3742-4bf5-8af9-2201792f42f3');
insert into produced_by (merchant_email, food_sn) values ('malaysian@google.com.au', '3b3a82f5-b0ef-4b27-94c4-8e8329218e20');
insert into produced_by (merchant_email, food_sn) values ('malaysian@google.com.au', '4059196d-cfab-4e05-bda0-7ac7e12d7a05');
insert into produced_by (merchant_email, food_sn) values ('japanese@plala.or.jp', '80c30ea4-f9f1-41ea-9828-8d185accf72a');
insert into produced_by (merchant_email, food_sn) values ('japanese@plala.or.jp', 'bcad25a0-1821-42b3-bd37-59804fdf281b');
insert into produced_by (merchant_email, food_sn) values ('chinese@senate.gov', '7ff5546c-df12-4eac-82c3-3624b2614acd');
insert into produced_by (merchant_email, food_sn) values ('chinese@senate.gov', '390fd66e-a161-4163-b863-776e6fc5773b');
insert into produced_by (merchant_email, food_sn) values ('fastfood4@comsenz.com', 'bda71065-8c9a-4c2e-9892-423089e6c2bf');
insert into produced_by (merchant_email, food_sn) values ('fastfood4@comsenz.com', '8d1eb5bb-3e5e-4b6a-becf-4feeb31e6920');
insert into produced_by (merchant_email, food_sn) values ('drinks@zdnet.com', 'c114705e-a977-4eb2-89e5-0b9ce7abe241');
insert into produced_by (merchant_email, food_sn) values ('drinks@zdnet.com', '80283e89-5b03-438b-b3e4-cd89e3ff4f57');
insert into produced_by (merchant_email, food_sn) values ('indian@reverbnation.com', '3cc2c734-8fb9-4eaf-9505-1d24b4d1207e');
insert into produced_by (merchant_email, food_sn) values ('indian@reverbnation.com', '03c1081f-dc0a-4301-9ca1-bf60cdf6bbdb');
insert into produced_by (merchant_email, food_sn) values ('dessert@quantcast.com', '30a7a274-775a-49ee-ae43-159bfac28857');
insert into produced_by (merchant_email, food_sn) values ('dessert@quantcast.com', 'a7727d9d-736a-427a-b6e0-23a0aa2f03d9');