insert into merchant (email, location) values ('western0@odnoklassniki.ru', 'West');
insert into merchant (email, location) values ('malaysian@google.com.au', 'North');
insert into merchant (email, location) values ('japanese@plala.or.jp', 'East');
insert into merchant (email, location) values ('chinese@senate.gov', 'East');
insert into merchant (email, location) values ('fastfood4@comsenz.com', 'West');
insert into merchant (email, location) values ('drinks@zdnet.com', 'Central');
insert into merchant (email, location) values ('indian@reverbnation.com', 'East');
insert into merchant (email, location) values ('dessert@quantcast.com', 'South');
insert into merchant (email, location) values ('anonymous_merchant', 'Central');
